# Generated by Django 5.1.5 on 2025-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departmant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50)),
                ('dep_des', models.TextField()),
                ('dep_hod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_dep', models.CharField(max_length=50)),
                ('student_roll', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='aadhar',
        ),
        migrations.DeleteModel(
            name='Aadhar',
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
