# Generated by Django 5.1.5 on 2025-01-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_departmant_student_remove_userprofile_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmant',
            name='dep_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.departmant', to_field='dep_name'),
        ),
    ]
