# Generated by Django 5.1.5 on 2025-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_departmant_dep_name_alter_student_student_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(choices=[('Tata', 'Tata'), ('BMW', 'BMW'), ('Audi', 'Audi')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_dep',
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(choices=[('Petrol', 'petrol'), ('Desel', 'Desel'), ('CNG', 'CNG'), ('EV', 'EV')], max_length=50)),
                ('v_nm', models.ManyToManyField(to='app.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Departmant',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
